version: '3.7'

services:

  application:
    container_name: application-woke
    restart: always
    build:
      context: .
      dockerfile: Dockerfile.local
    depends_on:
      - postgres
    ports:
      - 8080:8080
    environment:
      JDBC_URL: jdbc:postgresql://postgres:5432/woke
      SPRING_PROFILES_ACTIVE: local

  postgres:
    container_name: postgres-woke
    image: postgres:11-alpine
    volumes:
      - ./postgres-multiple-databases.sh:/docker-entrypoint-initdb.d/postgres-multiple-databases.sh
    command: [ "-c", "max_connections=200" ]
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_MULTIPLE_DATABASES=woke,woke_test
